FROM python:3.8-slim

RUN apt-get update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN cd ~ && \
    mkdir -p dlib && \
    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS

ENV APP_HOME main/
WORKDIR $APP_HOME

RUN pip3 install face_recognition tqdm

#COPY . .

#RUN unzip -q 16k_after_duplicates_resized_one_face_filter_hog_parsed_from_pinterest.zip && rm 16k_after_duplicates_resized_one_face_filter_hog_parsed_from_pinterest.zip
#RUN unzip -q resized_105_classes_pins_dataset.zip && rm resized_105_classes_pins_dataset.zip

#RUN mkdir data

ENTRYPOINT ["/bin/bash", "launch.sh"]
